#!/usr/bin/env python3
"""
Set up a review directory for a GitHub PR.

Usage:
    pr-review-preflight.py <PR_URL> [--repo-folder DIR] [--force]
    pr-review-preflight.py -R owner/repo --pr NUMBER [--repo-folder DIR] [--force]

Outputs the bare folder name (e.g. myrepo-pr123) to stdout on success.
All progress messages go to stderr.
"""

import argparse
import json
import re
import shutil
import subprocess
import sys
import textwrap
from html.parser import HTMLParser
from pathlib import Path

SCRATCHPAD = Path.home() / "scratchpad" / "pr_reviews"
DEFAULT_REPO_FOLDER = Path.home() / "repos"
SCRIPT_DIR = Path(__file__).parent
BUCKETS_FILE = SCRIPT_DIR / "pr-review-buckets.json"

DISCLAIMER = (
    "\n\n---\n\n"
    "> *This review was generated by an AI agent. "
    "Findings may be incomplete or incorrect. "
    "Use your own judgment before acting on any suggestion.*\n"
)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(
        description="Set up a PR review working directory.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("url", nargs="?", help="PR URL")
    p.add_argument("-R", "--repo", help="owner/repo (use with --pr)")
    p.add_argument("--pr", type=int, help="PR number (use with -R)")
    p.add_argument("--repo-folder", type=Path, default=DEFAULT_REPO_FOLDER,
                   help=f"Root folder for local clones (default: {DEFAULT_REPO_FOLDER})")
    p.add_argument("--force", action="store_true",
                   help="Delete an existing review directory and start fresh")
    return p.parse_args()


def parse_pr_url(url):
    m = re.match(r"https?://[^/]+/([^/]+/[^/]+)/pull/(\d+)", url)
    if not m:
        sys.exit(f"error: cannot parse PR URL: {url}")
    return m.group(1), int(m.group(2))


# ---------------------------------------------------------------------------
# Shell helpers
# ---------------------------------------------------------------------------

def gh(*args, input_data=None):
    """Run a gh command; exit on failure."""
    result = subprocess.run(
        ["gh", *args],
        capture_output=True, text=True,
        input=input_data,
    )
    if result.returncode != 0:
        sys.exit(f"gh error: {result.stderr.strip()}")
    return result.stdout


def run(*args, cwd=None, check=True):
    result = subprocess.run(args, capture_output=True, text=True, cwd=cwd)
    if check and result.returncode != 0:
        sys.exit(f"command failed ({' '.join(str(a) for a in args)}): {result.stderr.strip()}")
    return result


# ---------------------------------------------------------------------------
# HTML normalisation
# ---------------------------------------------------------------------------

class _StripHTML(HTMLParser):
    def __init__(self):
        super().__init__()
        self.parts = []

    def handle_data(self, data):
        self.parts.append(data)


def normalise_body(text):
    """Return (normalised_text, was_html)."""
    if not re.search(r"<[a-zA-Z]", text or ""):
        return text or "", False
    parser = _StripHTML()
    parser.feed(text)
    return "".join(parser.parts), True


# ---------------------------------------------------------------------------
# Change categorisation
# ---------------------------------------------------------------------------

def categorise_changes(changed_files, buckets_cfg):
    """Classify changed files into buckets and decide which lenses to run."""
    buckets_def = buckets_cfg["buckets"]
    lens_rules = buckets_cfg["lensRules"]

    buckets: dict[str, list[str]] = {b: [] for b in buckets_def}
    unknown_extensions: set[str] = set()

    for f in changed_files:
        path = Path(f)
        matched = False

        for bucket, rules in buckets_def.items():
            # Pattern match (substring in path string)
            for pattern in rules.get("patterns", []):
                if pattern in f:
                    buckets[bucket].append(f)
                    matched = True
                    break
            if matched:
                break

            # Extension match — try longest suffix first (.test.ts before .ts)
            name = path.name
            for ext in sorted(rules.get("extensions", []), key=len, reverse=True):
                if name.endswith(ext):
                    buckets[bucket].append(f)
                    matched = True
                    break
            if matched:
                break

        if not matched and path.suffix:
            unknown_extensions.add(path.suffix)

    populated = {b: files for b, files in buckets.items() if files}
    lenses: set[str] = set()
    for bucket in populated:
        lenses.update(lens_rules.get(bucket, []))

    rationale = (
        f"buckets present ({', '.join(populated.keys()) or 'none'}) "
        f"-> run: {', '.join(sorted(lenses)) or 'none'}"
    )

    return {
        "lensesToRun": sorted(lenses),
        "buckets": {b: files for b, files in buckets.items() if files},
        "unknownExtensions": sorted(unknown_extensions),
        "rationale": rationale,
    }


# ---------------------------------------------------------------------------
# Repo / worktree helpers
# ---------------------------------------------------------------------------

def ensure_clone(repo, repo_folder):
    """Ensure repo is cloned under repo_folder; return clone path."""
    repo_name = repo.split("/")[1]
    clone_path = repo_folder / repo_name

    if clone_path.exists():
        print(f"  fetching {clone_path} ...", file=sys.stderr)
        run("git", "-C", str(clone_path), "fetch", "--quiet", "origin")
    else:
        print(f"  cloning {repo} -> {clone_path} ...", file=sys.stderr)
        clone_path.parent.mkdir(parents=True, exist_ok=True)
        run("gh", "repo", "clone", repo, str(clone_path))

    return clone_path


def create_worktree(clone_path, worktree_path, commit_sha):
    run("git", "-C", str(clone_path),
        "worktree", "add", "--detach", str(worktree_path), commit_sha)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    args = parse_args()

    # Resolve repo + PR number
    if args.url:
        repo, pr_number = parse_pr_url(args.url)
    elif args.repo and args.pr:
        repo, pr_number = args.repo, args.pr
    else:
        sys.exit("error: provide a PR URL or both -R owner/repo and --pr NUMBER")

    repo_name = repo.split("/")[1]
    folder_name = f"{repo_name}-pr{pr_number}"
    review_dir = SCRATCHPAD / folder_name

    if review_dir.exists():
        if args.force:
            shutil.rmtree(review_dir)
        else:
            print(f"error: review directory already exists: {review_dir}", file=sys.stderr)
            print("Re-run with --force to delete and recreate.", file=sys.stderr)
            sys.exit(1)

    # Fetch PR metadata
    print(f"Fetching PR #{pr_number} from {repo} ...", file=sys.stderr)
    pr = json.loads(gh(
        "pr", "view", str(pr_number), "-R", repo,
        "--json",
        "title,body,headRefOid,headRefName,baseRefName,author,"
        "reviewThreads,labels,isDraft,state,url,number,files",
    ))

    changed_files = [f["path"] for f in pr.get("files", [])]

    # Determine if the PR is authored by the current user
    try:
        current_user = json.loads(gh("api", "user"))["login"]
    except SystemExit:
        current_user = None
    authored_by_self = pr["author"]["login"] == current_user if current_user else False

    # Normalise PR body
    raw_body = pr.get("body") or ""
    norm_body, was_html = normalise_body(raw_body)

    # Clone / update local repo and create isolated worktree
    print("Setting up git worktree ...", file=sys.stderr)
    clone_path = ensure_clone(repo, args.repo_folder)
    review_dir.mkdir(parents=True)
    worktree_path = review_dir / repo_name
    create_worktree(clone_path, worktree_path, pr["headRefOid"])

    # Generate diff
    print("Generating diff ...", file=sys.stderr)
    diff_result = run(
        "git", "-C", str(worktree_path),
        "diff", f"origin/{pr['baseRefName']}...HEAD",
        check=False,
    )
    (review_dir / "diff.txt").write_text(diff_result.stdout)

    # Categorise changes
    buckets_cfg = json.loads(BUCKETS_FILE.read_text())
    categorisation = categorise_changes(changed_files, buckets_cfg)

    # Preflight warnings
    preflight_warnings = []
    if pr.get("isDraft"):
        preflight_warnings.append("PR is a draft — review may be premature.")

    # Build pr-details.json
    pr_details: dict = {
        "github": {
            "number": pr_number,
            "repo": repo,
            "url": pr["url"],
            "title": pr["title"],
            "body": norm_body,
            "headRefOid": pr["headRefOid"],
            "headRefName": pr["headRefName"],
            "baseRefName": pr["baseRefName"],
            "author": pr["author"]["login"],
            "authoredBySelf": authored_by_self,
            "repoPath": str(worktree_path),
            "reviewThreads": pr.get("reviewThreads", []),
            "labels": [label["name"] for label in pr.get("labels", [])],
            "isDraft": pr.get("isDraft", False),
            "state": pr.get("state"),
            "changedFiles": changed_files,
            "changelog": [],
            "preflightWarnings": preflight_warnings,
        },
        "categorization": categorisation,
        "context": None,
    }

    if was_html:
        raw_path = review_dir / "pr-body-raw.md"
        raw_path.write_text(raw_body)
        pr_details["github"]["bodyRawPath"] = str(raw_path)

    (review_dir / "pr-details.json").write_text(
        json.dumps(pr_details, indent=2) + "\n"
    )

    # Scaffold pr-comments/
    comments_dir = review_dir / "pr-comments"
    comments_dir.mkdir()

    manifest = {
        "event": "COMMENT",
        "body_file": "body.md",
        "comments": [],
        "resolve_thread_ids": [],
    }
    (comments_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    (comments_dir / "body.md").write_text(
        "<!-- Write PR-level review summary above this line -->\n" + DISCLAIMER
    )

    # Create post-review.sh
    post_script = SCRIPT_DIR / "post-pr-review.py"
    post_review_sh = textwrap.dedent(f"""\
        #!/usr/bin/env bash
        set -euo pipefail
        DIR="$(cd "$(dirname "$0")" && pwd)"
        python3 {post_script} "$DIR"
    """)
    post_sh_path = review_dir / "post-review.sh"
    post_sh_path.write_text(post_review_sh)
    post_sh_path.chmod(0o755)

    print(f"Review directory: {review_dir}", file=sys.stderr)
    print(folder_name)


if __name__ == "__main__":
    main()
